/*
 * 橘瓣 OrangeChat
 * 衍生自 RikkaHub (https://github.com/rikkahub/rikkahub)，原作者 RE
 * 本项目基于 GNU AGPL v3 开源，详见根目录 LICENSE 文件
 */

package me.rerere.rikkahub.data.repository

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import me.rerere.rikkahub.data.db.dao.MemoryDAO
import me.rerere.rikkahub.data.db.entity.MemoryEntity
import me.rerere.rikkahub.data.model.AssistantMemory
import me.rerere.rikkahub.data.model.MemoryCategory

class MemoryRepository(private val memoryDAO: MemoryDAO) {
    companion object {
        const val GLOBAL_MEMORY_ID = "__global__"
    }

    fun getMemoriesOfAssistantFlow(assistantId: String): Flow<List<AssistantMemory>> =
        memoryDAO.getMemoriesOfAssistantFlow(assistantId)
            .map { entities -> entities.toAssistantMemories() }

    suspend fun getMemoriesOfAssistant(assistantId: String): List<AssistantMemory> {
        return memoryDAO.getMemoriesOfAssistant(assistantId).toAssistantMemories()
    }

    /**
     * 按优先级降序取出记忆，用于注入 system prompt：关键记忆排在最前面，
     * 长记忆列表被模型截断时也能优先保住重要信息。
     */
    suspend fun getMemoriesOfAssistantByPriority(assistantId: String): List<AssistantMemory> {
        return memoryDAO.getMemoriesOfAssistantByPriority(assistantId).toAssistantMemories()
    }

    fun getGlobalMemoriesFlow(): Flow<List<AssistantMemory>> =
        memoryDAO.getMemoriesOfAssistantFlow(GLOBAL_MEMORY_ID)
            .map { entities -> entities.toAssistantMemories() }

    suspend fun getGlobalMemories(): List<AssistantMemory> {
        return memoryDAO.getMemoriesOfAssistant(GLOBAL_MEMORY_ID).toAssistantMemories()
    }

    suspend fun getGlobalMemoriesByPriority(): List<AssistantMemory> {
        return memoryDAO.getMemoriesOfAssistantByPriority(GLOBAL_MEMORY_ID).toAssistantMemories()
    }

    private fun List<MemoryEntity>.toAssistantMemories(): List<AssistantMemory> =
        filterNot { it.isSummaryMemory() }.map { it.toAssistantMemory() }

    private fun MemoryEntity.toAssistantMemory(): AssistantMemory = AssistantMemory(
        id = id,
        content = content,
        category = MemoryCategory.fromSerialName(category),
        priority = priority,
        autoGenerated = autoGenerated,
    )

    private fun MemoryEntity.isSummaryMemory(): Boolean {
        return content.startsWith("[daily_summary]") ||
            content.startsWith("[phase_summary]") ||
            content.startsWith("[auto_summary]")
    }

    suspend fun deleteMemoriesOfAssistant(assistantId: String) {
        memoryDAO.deleteMemoriesOfAssistant(assistantId)
    }

    suspend fun updateContent(id: Int, content: String): AssistantMemory {
        val old = memoryDAO.getMemoryById(id) ?: error("Memory record #$id not found")
        val newMemory = old.copy(
            content = content
        )
        memoryDAO.updateMemory(newMemory)
        return newMemory.toAssistantMemory()
    }

    /**
     * 同时更新内容、分类与优先级。category / priority 传 null 表示保持原值。
     */
    suspend fun updateMemory(
        id: Int,
        content: String? = null,
        category: MemoryCategory? = null,
        priority: Int? = null,
    ): AssistantMemory {
        val old = memoryDAO.getMemoryById(id) ?: error("Memory record #$id not found")
        val newMemory = old.copy(
            content = content ?: old.content,
            category = category?.serialName ?: old.category,
            priority = (priority ?: old.priority).coerceIn(0, 2),
        )
        memoryDAO.updateMemory(newMemory)
        return newMemory.toAssistantMemory()
    }

    suspend fun updateCategory(id: Int, category: MemoryCategory) {
        memoryDAO.updateCategory(id, category.serialName)
    }

    suspend fun updatePriority(id: Int, priority: Int) {
        memoryDAO.updatePriority(id, priority.coerceIn(0, 2))
    }

    suspend fun addMemory(
        assistantId: String,
        content: String,
        category: MemoryCategory = MemoryCategory.GENERAL,
        priority: Int = AssistantMemory.PRIORITY_NORMAL,
        autoGenerated: Boolean = false,
    ): AssistantMemory {
        val entity = MemoryEntity(
            assistantId = assistantId,
            content = content,
            category = category.serialName,
            priority = priority.coerceIn(0, 2),
            autoGenerated = autoGenerated,
            createAt = System.currentTimeMillis(),
        )
        val newId = memoryDAO.insertMemory(entity).toInt()
        return entity.copy(id = newId).toAssistantMemory()
    }

    suspend fun deleteMemory(id: Int) {
        memoryDAO.deleteMemory(id)
    }
}
