package me.rerere.rikkahub.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class MemoryEntity(
    @PrimaryKey(true)
    val id: Int = 0,
    @ColumnInfo("assistant_id")
    val assistantId: String,
    @ColumnInfo("content")
    val content: String = "",
    /**
     * 记忆分类，取值见 [me.rerere.rikkahub.data.model.MemoryCategory] 的 serial name。
     * 空串按 GENERAL 处理，兼容旧数据。
     */
    @ColumnInfo("category", defaultValue = "general")
    val category: String = "general",
    /**
     * 优先级：0=普通，1=重要，2=关键。注入 prompt 时按此降序排序。
     */
    @ColumnInfo("priority", defaultValue = "0")
    val priority: Int = 0,
    /**
     * 是否由助手自动记录（memory_tool 写入）；false 表示用户手动添加。
     */
    @ColumnInfo("auto_generated", defaultValue = "0")
    val autoGenerated: Boolean = false,
    /**
     * 创建时间（毫秒）。0 表示旧数据未记录。
     */
    @ColumnInfo("create_at", defaultValue = "0")
    val createAt: Long = 0L,
)
